import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../../../styles/globals.scss";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopNav from "@/components/admin/TopNav";
import Sidebar from "@/components/admin/Sidebar";

import { Poppins, Sacramento } from "next/font/google";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-poppins",
    display: "swap",
});

const poppinsBold = Poppins({
    subsets: ["latin"],
    weight: ["700"],
    variable: "--font-poppins-bold",
    display: "swap",
});

const sacramento = Sacramento({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-sacramento",
    display: "swap",
});
export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};
export default async function AdminLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body
                className={`${poppins.variable} ${poppinsBold.variable} ${sacramento.variable} antialiased min-h-full flex flex-col overflow-hidden`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <TopNav />
                        <div className="flex flex-1">
                            <Sidebar />
                            <main className="flex-1 overflow-y-auto p-4">
                                {children}
                            </main>
                        </div>
                        <ToastContainer />
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
