import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../../../styles/globals.scss";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopNav from "@/components/admin/TopNav";
import Sidebar from "@/components/admin/Sidebar";
import "froala-editor/css/froala_style.min.css";
import "froala-editor/css/froala_editor.pkgd.min.css";
import { Poppins, Sacramento } from "next/font/google";
import { DataProvider } from "@/app/context/AppContext";
import { cookies } from "next/headers";
import AppProvider from "@/app/context/AppProvider";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-poppins",
    display: "swap",
});

const poppinsBold = Poppins({
    subsets: ["latin"],
    weight: ["700"],
    variable: "--font-poppins-bold",
    display: "swap",
});

const sacramento = Sacramento({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-sacramento",
    display: "swap",
});
export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};
export default async function AdminLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();
    const cookieStore = cookies();
    const sessionToken = cookieStore.get("sessionToken");
    return (
        <html lang={locale}>
            <body
                className={`${poppins.variable} ${poppinsBold.variable} ${sacramento.variable} antialiased h-full bg-secondary flex flex-col overflow-hidden`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <AppProvider initialSessionToken={sessionToken?.value}>
                            <DataProvider>
                                <TopNav />
                                <div className="flex flex-1">
                                    <Sidebar />
                                    <main className="flex-1 bg-secondary overflow-y-auto p-4 max-h-[calc(100vh-64px)]">
                                        <div className="h-full overflow-y-auto">
                                            {children}
                                        </div>
                                    </main>
                                </div>
                                <ToastContainer />
                            </DataProvider>
                        </AppProvider>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
