import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../../../styles/globals.scss";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopNav from "@/components/admin/TopNav";
import Sidebar from "@/components/admin/Sidebar";

export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};
export default async function AdminLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className="antialiased min-h-full flex flex-col overflow-hidden">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <TopNav />
                        <div className="flex flex-1">
                            <Sidebar />
                            <main className="flex-1 overflow-y-auto p-4">
                                {children}
                            </main>
                        </div>
                        <ToastContainer />
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
