/* eslint-disable @typescript-eslint/no-explicit-any */
import { CONSTANTS } from "@/utils/constants";
import { Fields } from "./fields";
import { locations } from "@/components/shared/Combobox";

export const userFields: Fields[] = [
    {
        name: "profilePic",
        label: "Profile Picture",
        type: "file",
        placeholder: "Upload profile picture",
        required: true,
        icon: "mdi:account-circle-outline",
    },
    {
        name: "email",
        label: "Email",
        type: "text",
        placeholder: "Enter email address",
        required: true,
        icon: "mdi:email-outline",
    },
    {
        name: "first_name",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        required: true,
        icon: "mdi:account-outline",
    },
    {
        name: "last_name",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        required: true,
        icon: "mdi:account-outline",
    },
    {
        name: "bio",
        label: "Bio",
        type: "text",
        placeholder: "Enter user bio",
        required: false,
        icon: "mdi:book-outline",
    },
];

export const tourFields: Fields[] = [
    {
        name: "thumbnail",
        label: "Thumbnails",
        type: "file",
        placeholder: "Select main thumbnails",
        required: true,
        icon: "mdi:image-outline",
        multiple: true,
    },

    {
        name: "photo",
        label: "Photo",
        type: "file",
        placeholder: "Upload tour picture",
        required: false,
        icon: "mdi:camera-outline",
    },
    {
        name: "title",
        label: "Title",
        type: "text",
        placeholder: "Enter tour title",
        required: true,
        icon: "mdi:format-title",
    },
    {
        name: "location",
        label: "Location",
        type: "text",
        placeholder: "Enter tour location",
        required: true,
        icon: "mdi:map-marker-outline",
    },
    {
        name: "price",
        label: "Price",
        type: "text",
        placeholder: "Enter tour price",
        required: true,
        icon: "mdi:currency-usd",
    },
    {
        name: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
        icon: "mdi:calendar-outline",
    },
    {
        name: "duration",
        label: "Duration (days)",
        type: "text",
        placeholder: "Enter tour duration in days",
        required: true,
        icon: "mdi:timer-outline",
    },
    {
        name: "rating",
        label: "Rating",
        type: "select",
        options: [
            { value: "1", label: "1 Star" },
            { value: "2", label: "2 Stars" },
            { value: "3", label: "3 Stars" },
            { value: "4", label: "4 Stars" },
            { value: "5", label: "5 Stars" },
        ],
        required: true,
        icon: "mdi:star-outline",
    },
    {
        name: "description",
        label: "Description",
        type: "text",
        placeholder: "Enter tour description",
        required: true,
        icon: "mdi:comment-outline",
    },
    {
        name: "typeId",
        label: "Tour Type ID",
        type: "text",
        placeholder: "Enter tour type ID",
        required: true,
        icon: "mdi:tag-outline",
    },
    {
        name: "packageId",
        label: "Package ID",
        type: "text",
        placeholder: "Enter package ID",
        required: true,
        icon: "mdi:package-variant-outline",
    },
    {
        name: "destinationId",
        label: "Destination ID",
        type: "text",
        placeholder: "Enter destination ID",
        required: true,
        icon: "mdi:map-marker-radius-outline",
    },
];

export const destinationFields: Fields[] = [
    {
        name: "photo",
        label: "Photo",
        type: "file",
        placeholder: "Select photo",
        required: true,
        icon: "mdi:image-outline",
        // multiple: true,
    },
    {
        name: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter destination name",
        required: true,
        icon: "mdi:format-title",
    },
    {
        name: "description",
        label: "Description",
        type: "text",
        placeholder: "Enter destination description",
        required: true,
        icon: "mdi:comment-outline",
    },
];

export const bookingFields: Fields[] = [
    {
        name: "location",
        label: "Location",
        type: "select",
        options: locations.map((type: any) => ({
            value: type.value,
            label: type.label,
        })),
        required: true,
        icon: "mdi:map-marker-outline",
    },
    {
        name: "number_of_travelers",
        label: "Number of Travelers",
        type: "text",
        placeholder: "Enter number of travelers",
        required: true,
        icon: "mdi:account-multiple-outline",
    },
    {
        name: "tour_type",
        label: "Tour Type",
        type: "select",
        options: CONSTANTS.TOUR_TYPES.map((type: any) => ({
            value: type.value,
            label: type.label,
        })),
        required: true,
        icon: "mdi:format-list-bulleted-square",
    },
    {
        name: "travel_class",
        label: "Travel Class",
        type: "select",
        options: Object.keys(CONSTANTS.TOUR_CLASS_PRICES).map((classType) => ({
            value: classType,
            label: `${classType.charAt(0).toUpperCase()}${classType.slice(
                1
            )} Class`,
        })),
        required: true,
        icon: "mdi:format-list-numbered-circle",
    },
    {
        name: "checkin_date",
        label: "Check-In Date",
        type: "date",
        required: true,
        icon: "mdi:calendar-range-outline",
    },
    {
        name: "checkout_date",
        label: "Check-Out Date",
        type: "date",
        required: true,
        icon: "mdi:calendar-range-outline",
    },
    {
        name: "full_name",
        label: "Full Name",
        type: "text",
        placeholder: "Enter full name",
        required: true,
        icon: "mdi:account-outline",
    },
    {
        name: "email",
        label: "Email",
        type: "text",
        placeholder: "Enter email address",
        required: true,
        icon: "mdi:email-outline",
    },
    {
        name: "phone_number",
        label: "Phone Number",
        type: "text",
        placeholder: "Enter phone number",
        required: true,
        icon: "mdi:phone-outline",
    },
    {
        name: "passport_number",
        label: "Passport Number",
        type: "text",
        placeholder: "Enter passport number",
        required: true,
        icon: "mdi:passport-outline",
    },
    {
        name: "nationality",
        label: "Nationality",
        type: "text",
        placeholder: "Enter nationality",
        required: true,
        icon: "mdi:earth-outline",
    },
    {
        name: "dietary_restrictions",
        label: "Dietary Restrictions",
        type: "text",
        placeholder: "Enter dietary restrictions",
        required: false,
        icon: "mdi:food-variant-outline",
    },
    {
        name: "emergency_name",
        label: "Emergency Contact Name",
        type: "text",
        placeholder: "Enter emergency contact name",
        required: true,
        icon: "mdi:account-alert-outline",
    },
    {
        name: "emergency_phone",
        label: "Emergency Contact Phone",
        type: "text",
        placeholder: "Enter emergency contact phone number",
        required: true,
        icon: "mdi:phone-outline",
    }
];
