import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../../styles/globals.scss";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/shared/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



export const metadata: Metadata = {
    title: "Travel Booking",
    description: "Generated by create next app",
};
export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className="antialiased">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <Header />
                        {children}
                        <ToastContainer />
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
