import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../../styles/globals.scss";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/shared/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/shared/Footer";
import { Poppins, Sacramento } from "next/font/google";
import AppProvider from "@/app/context/AppProvider";
import { cookies } from "next/headers";
import { DataProvider } from "@/app/context/AppContext";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-poppins",
    display: "swap",
});

const poppinsBold = Poppins({
    subsets: ["latin"],
    weight: ["700"],
    variable: "--font-poppins-bold",
    display: "swap",
});

const sacramento = Sacramento({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-sacramento",
    display: "swap",
});
export const metadata: Metadata = {
    title: "Travel Booking",
    description: "Generated by create next app",
};
export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();
    const cookieStore = cookies();
    const sessionToken = cookieStore.get("sessionToken");
    return (
        <html lang={locale}>
            <body
                className={`${poppins.variable} ${poppinsBold.variable} ${sacramento.variable} antialiased bg-secondary`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <AppProvider initialSessionToken={sessionToken?.value}>
                            <DataProvider>
                                <Header />
                                {children}
                                <Footer />
                                <ToastContainer />
                            </DataProvider>
                        </AppProvider>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
