import { ThemeProvider } from "@/components/shared/ThemeProvider";
import "../../styles/globals.scss";
import localFont from "next/font/local";
import { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/shared/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const poppins = localFont({
    src: "../fonts/Poppins.woff",
    variable: "--font-poppins-regular",
    weight: "400",
});

export const poppinsBold = localFont({
    src: "../fonts/Poppins-Black.woff",
    variable: "--font-poppins-bold",
    weight: "700",
});

const sacramento = localFont({
    src: "../fonts/Sacramento.woff",
    variable: "--font-sacramento",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Travel Booking",
    description: "Generated by create next app",
};
export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body
                className={`${poppins.variable} ${poppinsBold.variable}  ${sacramento.variable} antialiased `}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider messages={messages}>
                        <Header />
                        {children}
                        <ToastContainer />
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
